# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
    ]
